version: '3'
services:
  app:
    build: .
    labels:
        - "traefik.enable=true"
        - "traefik.backend=coapi"
        - "traefik.backend.healthcheck.path=/health"
        - "traefik.backend.healthcheck.interval=1s"
        - "traefik.frontend.rule=Host:localhost"
        - "traefik.port=8081"
    networks:
        - traefik
    
networks:
    traefik:
        external:
            name: traefik_webgateway
