version: '3'

services:
    traefik:
        image: traefik:v1.7
        networks:
            - webgateway
        ports:
            - "81:81"
            - "8090:8090"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ./traefik.toml:/traefik.toml

networks:
    webgateway:
        driver: bridge
